# Generated by Django 3.0.5 on 2020-04-13 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deriveweb', '0002_derivehome_image_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeriveBeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=100)),
                ('image_file', models.ImageField(upload_to='deriveweb/static/img')),
            ],
        ),
    ]
